### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by FT-Zheng** [Gofinge/PointTransformerV2#1]
Hello, may I ask when would the paper be uploaded to arxiv? I am looking forward to your work!

**Comment by Gofinge** [comment]
Thank you for your interest in our research,  and our paper will be available soon. The deadline for camera-ready is 12th Oct, and our paper's Arxiv version will be released at that time. :)

**Comment by Gofinge** [comment]
Thanks for your interest again, our [paper](https://arxiv.org/abs/2210.05666) has been uploaded to Arxiv.

**Comment by FT-Zheng** [comment]
> Thanks for your interest again, our [paper](https://arxiv.org/abs/2210.05666) has been uploaded to Arxiv.

Thank you!
