### ISSUE TITLE
How can I download ScanNet v2 dataset？

### ISSUE THREAD

**Issue by linhaojia13** [Gofinge/PointTransformerV2#18]
Hi, I fill out the agreement to the [ScanNet Terms of Use](http://kaldir.vc.in.tum.de/scannet/ScanNet_TOS.pdf) and send it to [scannet@googlegroups.com](mailto:scannet@googlegroups.com). 
After that, I receive an email which provides several ways to download the dataset, which is as follow:
```
Script usage:
- To download the entire ScanNet release (1.3TB): download-scannet.py -o [directory in which to download] 
- To download a specific scan (e.g., scene0000_00): download-scannet.py -o [directory in which to download] --id scene0000_00
- To download a specific file type (e.g., *.sens, valid file suffixes listed [here](https://github.com/scannet/scannet#data-organization)): download-scannet.py -o [directory in which to download] --type .sens
- To download the ScanNet v1 task data (inc. trained models): download-scannet.py -o [directory in which to download] --task_data
-  Train/test splits are given in the main ScanNet project repository: https://github.com/ScanNet/ScanNet/tree/master/Tasks/Benchmark
- ScanNet200 preprocessing information: https://github.com/ScanNet/ScanNet/tree/master/BenchmarkScripts/ScanNet200; to download the label map file: download-scannet.py -o [directory in which to download] --label_map
```
Which one should I choose? Should I download the `entire ScanNet release (1.3TB)` as the first one suggests?

**Comment by Gofinge** [comment]
Hi, the first one.

**Comment by linhaojia13** [comment]
> Hi, the first one.

Thank you very much!

**Comment by linhaojia13** [comment]
@Gofinge Hi, the download has always been interrupted. Could you please provide the pre-processed documents (via Baidu yun or Google drive)?

**Comment by Gofinge** [comment]
Hi, due to the ScanNet Terms of Use, I can not provide public distribution of this dataset.

**Comment by linhaojia13** [comment]
OK, thank you!
