### ISSUE TITLE
I am here to support your paper and waiting for your excellent code

### ISSUE THREAD

**Issue by yuchenlichuck** [Gofinge/PointTransformerV2#2]
**I am here to support your paper and waiting for your excellent code**
😃

**Comment by Gofinge** [comment]
Thanks for your appreciation, we will notify you when our codebase is ready :)

**Comment by Gofinge** [comment]
Hi @yuchenlichuck 

Thanks for the long time waiting. The code has been released, and I will close the issue. Hope the code will be helpful to your work. If you have any questions or suggestions, please feel free to open an issue or email me.
