### ISSUE TITLE
Nvidia driver version

### ISSUE THREAD

**Issue by linhaojia13** [Gofinge/PointTransformerV2#24]
@Gofinge Hi, to minimize differences between my experimental environment and yours, I would like to use the same version of the Nvidia driver as you. Could you please let me know which version you are using?

**Comment by Gofinge** [comment]
Hi, Here is the information:
```
Driver Version: 470.57.02
Cuda Version: 11.1
Cudnn Version: unknown
```

Actually, it should be no much difference between different drivers.

**Comment by linhaojia13** [comment]
Thank you！
