### ISSUE TITLE
modelnet40 voxelization 

### ISSUE THREAD

**Issue by JJBUP** [Gofinge/PointTransformerV2#29]
Why does the ModelNet40 need voxelization during training and not during validation and testing, while S3DIS training and validation and testing need voxelization.
My question appears in config/_ base_/ modelnet40.py.
We look forward to your reply
Thank you!

**Comment by Gofinge** [comment]
Hi, because ModelNet40 has 10,000 points/data, while S3DIS has 1,000,000 points/scene.

**Comment by JJBUP** [comment]
Therefore, we use the voxelized data for training, and the non-voxelized data for validation and testing. 
Will different densities of data not affect the validation and testing results？🧐

**Comment by Gofinge** [comment]
Maybe the instruction here can solve you double: 
https://github.com/Gofinge/PointTransformerV2#testing;

Also, another special tech which enabled here can acquire precise eval results during training: 
https://github.com/Gofinge/PointTransformerV2/blob/main/configs/scannet/semseg-ptv2m2-2-precise-evaluate.py
