### ISSUE TITLE
Is there something wrong with package name 'ftermcolor' , should it be replaced by 'termcolor'?

### ISSUE THREAD

**Issue by eva-yx-wang** [Gofinge/PointTransformerV2#30]
Thank you for your contributions!

(pctv2) wyx@ECCV:/data/wyx$ conda install sharedarray  yapf addict einops ftermcolor  -c conda-forge  -y
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ftermcolor

this commandis is better replaced with 'conda install yapf addict einops termcolor  -c conda-forge  -y' according to my practice, hope for opnion adoption, thank you!

**Comment by Gofinge** [comment]
Hi, I checked the Readme, and it should be correct. Still, thanks for your kindly remind!

![image](https://user-images.githubusercontent.com/39218229/225239912-f9da4eb2-df86-48bd-b93e-1175f081987b.png)

**Comment by eva-yx-wang** [comment]
Oops, it's my mistake, thank you for prompt reply !
