### ISSUE TITLE
s3dis preprocess

### ISSUE THREAD

**Issue by FT-Zheng** [Gofinge/PointTransformerV2#38]
When preprocess Stanford3dDataset_v1.2_Aligned_Version using python pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py --dataset_root ${RAW_S3DIS_DIR} --output_root ${PROCESSED_S3DIS_DIR}, i meet an error
`
Traceback (most recent call last):
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 114, in <module>
    main_process()
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 93, in main_process
    if "Aligned_Version" in opt.source_root:
AttributeError: 'Namespace' object has no attribute 'source_root'
`

**Comment by Gofinge** [comment]
Hi, thanks for your kind reminder and I have fixed the bug. Also, you can try our new advanced preprocessing script for S3DIS in [Pointcept](https://github.com/Pointcept/Pointcept/blob/main/pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py).

**Comment by FT-Zheng** [comment]
Thank you for your reply. 
I have noticed a new data processing script for S3DIS in pointcept, and I would like to know if ptv2 will perform better when using the new data processing？Can you briefly explain the differences between the new way of data processing and the previous one？
If I download Stanford 3dDataset_ v1.2_ Aligned_ Version.zip, do I only need to add "-- align_angle" to the command, and if I download the Standard3dDataset_ V1.2.zip does not require the addition of "-- align_angle".

**Comment by Gofinge** [comment]
```
Can you briefly explain the differences between the new way of data processing and the previous one？
```
1. Only use the non-aligned version dataset and aligned angle by rotation on  non-aligned version raw data;
2. Render normal vectors as what I introduced in ScanNet.

```
if ptv2 will perform better when using the new data processing？
```
Training on S3DIS is not stable, but I observed that the introducing of normal reduces overfitting. (You need to enable normal in the config, refer to the following config file https://github.com/Pointcept/Pointcept/blob/main/configs/s3dis/semseg-spunet-v1m1-0-cn-base.py)

**Comment by FT-Zheng** [comment]
Thank you very mcuh!

**Comment by FT-Zheng** [comment]
Thank you very much!

**Comment by FT-Zheng** [comment]
May I ask if the Stanford2d3dDataset_noXYZ dataset was downloaded from here?
![image](https://user-images.githubusercontent.com/94618716/233897465-9cee996c-35eb-4093-b5ca-e70ccf565b5d.png)

**Comment by Gofinge** [comment]
Yes.
