### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by GordonGuo98** [Gofinge/PointTransformerV2#4]
Thanks for your research! Will the code be released recently?

**Comment by Gofinge** [comment]
Yes, I just return from the conference, codebase optimizing and testing is on going now. I will keep the issue opening until code released.

**Comment by xiaobaitu123344** [comment]
+1，Thanks for your research!

**Comment by Gofinge** [comment]
@GordonGuo98 @xiaobaitu123344 Bad news, I just tested positive for Covid 19, so the code release process might slow down. PTv2 was the work that was finished half a year ago. My codebase has evolved after PTv2, and I want to bring the latest codebase framework to you. Consequently, vary from regular code cleaning for code release, I still need some tests for all released characteristics of my codebase. I really hope the codebase will be helpful to your research.

**Comment by GordonGuo98** [comment]
> @GordonGuo98 @xiaobaitu123344 Bad news, I just tested positive for Covid 19, so the code release process might slow down. PTv2 was the work that was finished half a year ago. My codebase has evolved after PTv2, and I want to bring the latest codebase framework to you. Consequently, vary from regular code cleaning for code release, I still need some tests for all released characteristics of my codebase. I really hope the codebase will be helpful to your research.

I'm sorry to hear that. Wishing you a speedy recovery!

**Comment by xiaobaitu123344** [comment]
Thanks for your research! Will the code be released recently?

**Comment by Gofinge** [comment]
Yes, It will be released in a few days.

**Comment by xiaobaitu123344** [comment]
🙏

**Comment by CanBaBa0517** [comment]
Hello, may I ask when will the code of point transformer v1 be released？

**Comment by Gofinge** [comment]
Hi, actually, the postech released PTv1 code was almost the original one. The PTv2 code will be released today.

**Comment by Gofinge** [comment]
Hi, @GordonGuo98 @xiaobaitu123344 @CanBaBa0517 

Thanks for the long time waiting. The code has been released, and I will close the issue. Hope the code will be helpful to your work. If you have any questions or suggestions, please feel free to open an issue or email me.
