### ISSUE TITLE
The difference between PTV2m1 and PTV2m2.

### ISSUE THREAD

**Issue by mrsempress** [Gofinge/PointTransformerV2#42]
What is the difference between PTV2m1 and PTV2m2? And which one is reported in the paper?

**Comment by Gofinge** [comment]
Hi, the difference is reported [here](https://github.com/Gofinge/PointTransformerV2#point-transformer-v1--v2). v2m1 is reported in paper, v2m2 is refined for 3090 * 4 (v2m2 should be better).

**Comment by mrsempress** [comment]
Thanks.
