### ISSUE TITLE
About Patch Partition

### ISSUE THREAD

**Issue by Litoda** [Gofinge/PointTransformerV2#48]
Hello, may I ask, if the partition-based pooling/ patch division only happens at the beginning, because it seems not able to apply to latent space? 
If not, how to apply this grid pooling on latent space? I didn't get it from reading paper.

**Comment by Gofinge** [comment]
It should be available to any point cloud at an encoding stage. Check our PTv2 & PTv3 code. https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/point_transformer_v2/point_transformer_v2m2_base.py#L229

**Comment by Litoda** [comment]
Does this mean that during grid pooling at any stage, the coordinates of the initial points will follow along with the features?

**Comment by Gofinge** [comment]
Yes, coordinates go with mean pooling.

**Comment by Litoda** [comment]
Thank you so much!!!
