### ISSUE TITLE
pe_multiplier=False,

### ISSUE THREAD

**Issue by hnuhyuwa** [Gofinge/PointTransformerV2#6]
Hi, thank you for your code. I find that the 'pe_multiplier' is set to 'False'. Do you apply this multiplier during training?

**Comment by Gofinge** [comment]
Hi, Please refer explanation [here](https://github.com/Gofinge/PointTransformerV2#point-transformer-v1--v2), PTv2m2 disable PEM & Gouped Linear to reduce the memory cost, make our model available on 4 * 24G GPUs, and we reproduced a better performance.

The original PTv2 we reported in paper is PTv2m1, the config is also available in model zoo.

**Comment by Gofinge** [comment]
I hope our PTv2 can be more available to most of us, consequence, combining my latest experiment results, I retune the model to reduce the cost.

**Comment by hnuhyuwa** [comment]
Thank you for your reply.
