### ISSUE TITLE
S3DIS Preprocessing ERROR (Wrong number of columns at line 180389)

### ISSUE THREAD

**Issue by BigBigWind** [Gofinge/PointTransformerV2#8]
cann't find

**Comment by Gofinge** [comment]
Hi, As mentioned in `README.md`, the original S3DIS data contains some bugs data need to fix it manually. You can refer discussion [here](https://github.com/JonasSchult/Mask3D/issues/8#issuecomment-1279167328) in Mask3d repo.

**Comment by BigBigWind** [comment]
thanks
